name: Create Merge Request

on:
  push:
    branches:
      - '*' 
      - '!main'
      - '!staging'

jobs:
  create-pr:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          base: staging
          branch: ${GITHUB_REF#refs/heads/}
          commit-message: ${{ github.event.head_commit.message }}
          title: Merge ${GITHUB_REF#refs/heads/} into staging
          draft: false
          delete-branch: true