name: Create Merge Request

on:
  push:
    branches:
      - '*' 

jobs:
  create-merge-request:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Merge Request
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b staging # Replace with your target branch name
          git push origin HEAD:staging -o merge_request.create